# Generated by Django 5.0.6 on 2024-08-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["pk"]},
        ),
    ]
